### ISSUE TITLE
JunOS error

### ISSUE THREAD

**Issue by valdr** [sebrupik/csc_scripts#1]
When I run the script on my SRX100H2, I get the following error after a while:
=====================================================================
Timed-out reading channel, data not available.
Traceback (most recent call last):
  File "cb.py", line 77, in <module>
    main()
  File "cb.py", line 63, in main
    tar_file = tarfile.open("./output/{0}".format(tarfile_name), "w:gz")
  File "/usr/lib64/python3.6/tarfile.py", line 1591, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib64/python3.6/tarfile.py", line 1638, in gzopen
    fileobj = gzip.GzipFile(name, mode + "b", compresslevel, fileobj)
  File "/usr/lib64/python3.6/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: './output/configs-2020-11-19-1511.tar.gz'
=====================================================================

Where is this file supposed to be created?

**Comment by sebrupik** [comment]
Hi there,
A slight omission in the the script! Make sure you have a directory named 'output' at the same location you run the script from.

cheers,
Seb.

**Comment by valdr** [comment]
Hello,

That error has now gone.
Instead I get a different error now.
I'll have to open a new issue to keep issues separated.

I'll think about cloning/forking to add the ./output folder if it's not present.

**Comment by sebrupik** [comment]
Glad you got it working. Feel free to clone this project and create a pull request :)
